{% set name = "cram" %}
{% set version = "0.7" %}
{% set bundle = "tar.gz" %}
{% set hash = "7da7445af2ce15b90aad5ec4792f857cef5786d71f14377e9eb994d8b8337f2f" %}
{% set build = 2 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}

  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - cram

  commands:
    - cram -h

about:
  home: https://bitheap.org/cram/
  license: GPL-2.0
  license_file: COPYING.txt
  summary: 'A simple testing framework for command line applications'
  license_family: GPL2
  dev_url: https://github.com/brodie/cram

extra:
  recipe-maintainers:
    - nehaljwani
