travis:
  secure:
    BINSTAR_TOKEN: ZlY+79a0SyYXrr+reKHhB0XboQIgh97GZphmwBJussj+iCbRdbn05DBVLQtxEwENlNxyYgFVSeJCV1Zi3dHryr4GovfocmfAeaROkpPFWVzXUcL/AcWWSN4bn1A/FLrSu8l9dDtxDd9An25XMvaJU4/Qi0ptvE9UvhWkpblrLYMFtD88wkyhVWKU6R1WGuDLs9ykcv/PTg+zvFo5U1SVTAN/425MESzXb5pzjkU0GdEeac7M7/yDvGlqML7PGXIevsLhJEKOCvdOUrL0F3038lY5J+Q5a8S4+I0qRqceayrENKElG7Vt2nrV64WQXi/QOI/wYFBnBevZBW+0lMlMh2Ilqu0JcrSRU5Ss/l9E2BxT3+Xmilj72cKuKP6SUnerUmefAiqs+iax9VDet3G/JWEmS65IBU6iV4E647Q+nbIvx5mMayza5UcK3z93B9lWd4NZUfokObLsjM/oi+/EiHR6lOWtusAZDmRzZm+vt9H3w+lbnApC5BjlQmIk78PWrhkbOqgwsWhK0/NkoOI0zKwO18LCK03/M/+vBG++JDt2h3+RUhKWBn7MYJmLoDu5m3ygGGdJPNdAvFXrqjS+bgVDVrkmm/wzb/cgPlpXoZYC837vQd70XXfRXVnTGQs6hyll1piXTKubdgCS5H/6ZFqAZi5CUcykryBYCTKwenY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
